name: crud-pacientes

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-appdb}

    ports:
      - "5433:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - rede_db

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ../api

    restart: unless-stopped

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_NAME: ${DB_NAME:-appdb}

    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy

    networks:
      - rede_db
      - rede_front

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1:3000/patients > /dev/null || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s

  front:
    build:
      context: ../front

    restart: unless-stopped

    ports:
      - "8080:80"

    depends_on:
      api:
        condition: service_healthy

    networks:
      - rede_front

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://127.0.0.1/ > /dev/null || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

networks:
  rede_db:
  rede_front:
